
# Gin-Vue-Admin Global Configuration
server:
  router: '8.137.93.135:8090'
# jwt configuration
jwt:
  signing-key: 'sciproj'

token:
  ExpiresDays: 30  #过期时间分钟

custom:
  prefix: sci_

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[SCIProj->]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true


# mysql connect configuration
mysql:
  path: '172.29.19.235:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'sciproj'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false


# redis configuration
redis:
  db: 0
  addr: '172.29.19.235:6379'
  password: ''