DROP DATABASE IF EXISTS SCIProj;
CREATE DATABASE SCIProj;
USE SCIProj;

CREATE TABLE ARTICLES (
    `PID` VARCHAR(10) PRIMARY KEY,
    `TITLE` VARCHAR(100),
    `REQUEST` VARCHAR(100),
    `CONTENT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    `TEACHER` VARCHAR(10),
    `STUDENT` VARCHAR(10),
    `CREATETIME` DATETIME not null,
    `UPDATETIME` DATETIME not null,
    `DELETETIME` DATETIME
)ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE TEACHERS(
    `TEACHERID` VARCHAR(10) PRIMARY KEY,
    `USERNAME` VARCHAR(10),
    `PASSWORD` VARCHAR(10),
    `EMAIL` VARCHAR(20),
    `PHONE` VARCHAR(20),
    `ROLE` VARCHAR(10),
    `AVATAR` VARCHAR(100),
    `AGE` INT
)ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE STUDENTS(
     `STUDENTID` VARCHAR(10) PRIMARY KEY,
     `USERNAME` VARCHAR(10),
     `PASSWORD` VARCHAR(10),
     `EMAIL` VARCHAR(20),
     `PHONE` VARCHAR(20),
     `ROLE` VARCHAR(10),
     `AVATAR` VARCHAR(100),
     `AGE` INT,
     `MYTEACHER` VARCHAR(10)
)ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
